### ISSUE TITLE
No details on how to create custom tables

### ISSUE THREAD

**Issue by verrator** [pherbers/BehindTheTablesApp#1]
The link to the custom tables wiki is a dead page. Would be nice if step by step instruction for those of us unfamiliar with creating json files could be shown how to create our own tables.

**Comment by pherbers** [comment]
Hi @verrator

I am surprised that this app still has active users! Thanks for the support :)

I have had an update for the app in my queue for quite some time, including the feature of creating and editing custom tables inside the app. I've had some troubles getting the update pushed out to the Play Store since I had to reset my keys. I'll keep this issue open until that is resolved and the update is released.

Best, Patrick

**Comment by verrator** [comment]
Great to hear you guys are still working on it. Yes please keep me updated,
i look forward to hearing from you.

**Comment by pherbers** [comment]
@verrator I've pushed an update to the play store on the open beta channel (you can activate it in Google Play). Custom tables can now be created using the (+) button in the app bar, and you can import and export to zip in the settings. Let me know if there are any problems, otherwise I'll push the app to production.

**Comment by verrator** [comment]
Thank you for your reply. The update works, I appreciate your help.

Regards,

Reece

**Comment by pherbers** [comment]
Great! I've sent the update out to production.

Best, Patrick

**Comment by verrator** [comment]
Just had an idea this morning. How hard would it be to add an option to
export out custom made tables to make it easy to share new tables with
other users?
